// ---------- multiple zeros and poles ----------
function groups(kind){return kind==="zero"?state.zeroGroups:state.poleGroups}function points(kind){return kind==="zero"?state.zeros:state.poles}
function groupMembers(kind,index){const g=groups(kind),id=g[index];return g.map((x,i)=>x===id?i:-1).filter(i=>i>=0)}function freshGroupId(g){return g.length?Math.max(...g)+1:0}
function nearestSnap(kind,index){const pts=points(kind),g=groups(kind),own=g[index],p=toScreen(pts[index]);let best=-1,bd=17;for(let i=0;i<pts.length;i++)if(g[i]!==own){const q=toScreen(pts[i]),d=Math.hypot(p.x-q.x,p.y-q.y);if(d<bd){bd=d;best=i}}return best}
function mergeGroup(kind,index,target){const pts=points(kind),g=groups(kind),a=g[index],b=g[target],id=Math.min(a,b),at=clone(pts[target]);for(let i=0;i<g.length;i++)if(g[i]===a||g[i]===b){g[i]=id;pts[i]=clone(at)}recompute()}
function unsnap(kind,index){const mem=groupMembers(kind,index);if(mem.length<=1)return false;const pts=points(kind),g=groups(kind),center=clone(pts[index]),px=2*state.view.half/Math.min(plot.clientWidth,plot.clientHeight),r=px*(mem.length===2?10:12);let id=freshGroupId(g);mem.forEach((i,k)=>{pts[i]=add(center,scale(expi(2*Math.PI*k/mem.length-Math.PI/2),r));g[i]=id++});recompute();return true}

// ---------- SVG and status ----------
function drawDiamond(p,r,cls){return svgEl("path",{d:`M ${p.x} ${p.y-r} L ${p.x+r} ${p.y} L ${p.x} ${p.y+r} L ${p.x-r} ${p.y} Z`,class:cls})}
function renderSvg(quality){
  const{w,h}=dims(plot);svg.setAttribute("viewBox",`0 0 ${w} ${h}`);clearSvg();drawGrid();if(state.dataDirty||!state.flow){state.flow=computeFlow(quality);state.dataDirty=false}
  if(document.getElementById("diskToggle").checked){const q=state.flow.disk,p=toScreen(q.center),ppu=Math.min(w,h)/(2*state.view.half);svg.appendChild(svgEl("circle",{cx:p.x,cy:p.y,r:q.radius*ppu,class:"enclosing-disk"}));svg.appendChild(svgEl("line",{x1:p.x-5,y1:p.y,x2:p.x+5,y2:p.y,class:"disk-center"}));svg.appendChild(svgEl("line",{x1:p.x,y1:p.y-5,x2:p.x,y2:p.y+5,class:"disk-center"}))}
  if(document.getElementById("graphToggle").checked){for(const b of state.flow.branches.filter(x=>x.type==="pole"))for(const seg of b.segments)if(seg.length>1)svg.appendChild(svgEl("path",{d:pathString(seg),class:`flow ${b.resolved?"from-pole":"unresolved"}`}));for(const b of state.flow.branches.filter(x=>x.type==="zero"))for(const seg of b.segments)if(seg.length>1)svg.appendChild(svgEl("path",{d:pathString(seg),class:`flow ${b.resolved?"to-zero":"unresolved"}`}))}
  for(const w0 of state.critical){const p=toScreen(w0);svg.appendChild(svgEl("circle",{cx:p.x,cy:p.y,r:6.4,class:"critical-node"}))}
  for(const kind of ["pole","zero"]){const pts=points(kind),g=groups(kind),seen=new Set();pts.forEach((z,i)=>{const p=toScreen(z),mem=groupMembers(kind,i),gid=g[i];if(mem.length>1&&!seen.has(gid)){seen.add(gid);svg.appendChild(svgEl("circle",{cx:p.x,cy:p.y,r:12+Math.min(5,mem.length),class:"stack-ring"}))}const node=kind==="zero"?svgEl("circle",{cx:p.x,cy:p.y,r:7.4,class:"node zero-node draggable"}):drawDiamond(p,8.2,"node pole-node draggable");node.dataset.kind=kind;node.dataset.index=i;node.addEventListener("pointerdown",startNodeDrag);svg.appendChild(node)})}
}
function updateStatus(){const finite=state.critical.length,total=2*state.degree-2,inf=Math.max(0,total-finite),resolved=state.flow?state.flow.branches.filter(b=>b.resolved).length:0,all=state.flow?state.flow.branches.length:0;document.getElementById("countStatus").textContent=`${state.degree}Z · ${state.degree}P · ${finite}C${inf?` · ${inf} at ∞`:""}`;const w=document.getElementById("warning");let msg=state.warning;if(all&&resolved<all)msg+=(msg?" ":"")+`${all-resolved} separatrix arm${all-resolved===1?"":"s"} did not reach a finite endpoint numerically.`;w.textContent=msg;w.classList.toggle("show",!!msg)}
function render(quality){drawContours(quality);renderSvg(quality);updateStatus()}function scheduleRender(full=false){state.fullRender=state.fullRender||full;if(state.renderQueued)return;state.renderQueued=true;requestAnimationFrame(()=>{state.renderQueued=false;const q=state.fullRender;state.fullRender=false;render(q)})}

// ---------- interaction ----------
function startNodeDrag(e){e.preventDefault();e.stopPropagation();const kind=e.currentTarget.dataset.kind,index=+e.currentTarget.dataset.index,p=eventPoint(e),mem=groupMembers(kind,index),pts=points(kind);state.dragging={kind,index,pointerId:e.pointerId,startX:p.x,startY:p.y,startWorld:fromScreen(p.x,p.y),members:mem,initial:mem.map(i=>clone(pts[i])),moved:false};e.currentTarget.setPointerCapture?.(e.pointerId)}
plot.addEventListener("pointerdown",e=>{if(e.button!==0||state.dragging||e.target.closest?.(".draggable"))return;e.preventDefault();const p=eventPoint(e);state.dragging={kind:"pan",pointerId:e.pointerId,startX:p.x,startY:p.y,cx:state.view.cx,cy:state.view.cy,half:state.view.half,moved:false};plot.classList.add("panning");plot.setPointerCapture?.(e.pointerId)});
window.addEventListener("pointermove",e=>{const d=state.dragging;if(!d||e.pointerId!==d.pointerId)return;const p=eventPoint(e),dx=p.x-d.startX,dy=p.y-d.startY;if(Math.hypot(dx,dy)>3)d.moved=true;if(d.kind==="pan"){const u=2*d.half/Math.min(plot.clientWidth,plot.clientHeight);state.view.cx=d.cx-dx*u;state.view.cy=d.cy+dy*u;scheduleRender(false);return}const target=fromScreen(p.x,p.y),delta=sub(target,d.startWorld),pts=points(d.kind);d.members.forEach((i,k)=>pts[i]=add(d.initial[k],delta));recompute();scheduleRender(false)});
window.addEventListener("pointerup",e=>{const d=state.dragging;if(!d||e.pointerId!==d.pointerId)return;if(d.kind==="pan")plot.classList.remove("panning");else if(!d.moved)unsnap(d.kind,d.index);else{const t=nearestSnap(d.kind,d.index);if(t>=0)mergeGroup(d.kind,d.index,t)}state.dragging=null;scheduleRender(true)});
window.addEventListener("pointercancel",()=>{state.dragging=null;plot.classList.remove("panning");scheduleRender(true)});
plot.addEventListener("wheel",e=>{e.preventDefault();const p=eventPoint(e),before=fromScreen(p.x,p.y),factor=Math.exp(Math.sign(e.deltaY)*.14);state.view.half=Math.max(.18,Math.min(100,state.view.half*factor));const after=fromScreen(p.x,p.y);state.view.cx+=before.re-after.re;state.view.cy+=before.im-after.im;scheduleRender(true)},{passive:false});
document.getElementById("degreeSelect").addEventListener("change",e=>reset(+e.target.value));document.getElementById("resetBtn").addEventListener("click",()=>reset(state.degree));document.getElementById("randomBtn").addEventListener("click",randomize);document.getElementById("fitBtn").addEventListener("click",fitView);for(const id of ["lemniscateToggle","graphToggle","diskToggle"])document.getElementById(id).addEventListener("change",()=>scheduleRender(true));new ResizeObserver(()=>scheduleRender(true)).observe(plot);reset(2);
